name: Run Unit Tests and Lint Files

on: push

jobs:
  unitTest-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Run Unit Tests and Lint Files
        run: |
          cd slugmart
          npm ci
          npm install util
          CI=false npm run build
          npm run lint
